server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:file:~/spring-boot-todomvc
    driver-class-name: org.h2.Driver
    username: todo
    password: sample
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
